# -- Local repository maps --
circle:
  map_path: './maps/circle/circle'
  map_ext: '.png'
  starting_poses: [[5.75, 0, 1.57]]
  max_timesteps: 1000

example:
  map_path: './maps/example/example_map'
  map_ext: '.png'
  starting_poses: [[0, 0, 1.57], [-1, 0, 0], [1, 0, 0], [0, 5, 1.57]]
  # starting_poses: [[0, 0, 1.57]]
  max_timesteps: 1000

reference:
  map_path: './maps/reference/reference'
  map_ext: '.png'
  starting_poses: [[-5.35, -0.75, 0.0]]
  # starting_poses: [[1.33, 1.17, 1.57]]
  max_timesteps: 1000

# -- Maps from Roemerlager

roemerlager:
  map_path: './maps/roemerlager/original'
  map_ext: '.png'
  starting_poses: [[0, 0, 0.0]]
  max_timesteps: 1000

roemerlager-wide:
  map_path: './maps/roemerlager/wide'
  map_ext: '.png'
  starting_poses: [[0, 0, 0]]
  max_timesteps: 1000

roemerlager-narrow:
  map_path: './maps/roemerlager/narrow'
  map_ext: '.png'
  starting_poses: [[0, 0, 0]]
  max_timesteps: 1000

roemerlager-cones-1:
  map_path: './maps/roemerlager/cones-1'
  map_ext: '.png'
  starting_poses: [[0, 0, 0]]
  max_timesteps: 1000

roemerlager-cones-2:
  map_path: './maps/roemerlager/cones-2'
  map_ext: '.png'
  starting_poses: [[0, 0, 0]]
  max_timesteps: 1000

roemerlager-cones-3:
  map_path: './maps/roemerlager/cones-3'
  map_ext: '.png'
  starting_poses: [[0, 0, 0]]
  max_timesteps: 1000

roemerlager-cones-4:
  map_path: './maps/roemerlager/cones-4'
  map_ext: '.png'
  starting_poses: [[0, 0, 0]]
  max_timesteps: 1000

roemerlager-cones-5:
  map_path: './maps/roemerlager/cones-5'
  map_ext: '.png'
  starting_poses: [[-5, 3.1, -1.57]]
  max_timesteps: 1000

# -- Maps provided by F1Tenth Racetracks Repo --

# Clone git@github.com:f1tenth/f1tenth_racetracks.git
# Replace the file paths

austin:
  map_path: '../f1tenth_racetracks/Austin/Austin_map'
  map_ext: '.png'
  starting_poses: [[-0.4108859, -0.6907978, 5.6364428]]
  max_timesteps: 1000
